### PR TITLE
Refactored main.py to use new modules, fixes for ints, cleaned up unused code

### PR DESCRIPTION
**Pull request by pnivek**
This change is to use the new modules: Journal and LLMParse which dramatically increase the speed and intent recognition of the natural language input. Also included fixes for existing integrations.

### CODE REVIEW

**Review by dot-Justin — APPROVED** [review]
Chef's kiss, thank you so much

**Review by glovergaytan-fs — APPROVED** [review]
reviewed

**Comment by glovergaytan-fs** [comment]
hehe

**Comment by dot-Justin** [comment]
good stuff guys

**Pull request merged**
