### PR TITLE
Not supported on mac

### PR DESCRIPTION
**Pull request by glovergaytan-fs**
Updated browser and computer modules to work for both pc and mac devices

### CODE REVIEW

**Comment by pnivek** [comment]
Hey @glovergaytan-fs , you gotta add some details to the PR of what was changed. Also these changes are two commits behind main, you have to rebase and pull in @dot-Justin 's changes to readme before we can review.

**Comment by glovergaytan-fs** [comment]
Updated browser and computer modules to work for both pc and mac devices

**Review by pnivek — APPROVED** [review]
LGTM!

**Review by dot-Justin — APPROVED** [review]
LGTM!
👍

**Pull request merged**
